name: Continuous Integration

on:
  push:
    branches: [main]
    paths-ignore:
      - 'openapi/**'
  pull_request:
  workflow_dispatch:

jobs:
  specifications-schema-validation:
    name: Validate specifications.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate specifications.yaml
        run: |
          ajv -d specifications.json -s ./schemas/specifications.schema.json --spec=draft2020 --errors=text
