name: Synchronize OpenApi specifications

on:
  schedule:
    - cron: '8 0 * * *' # At 08:00 every day
  push:
    branches: [ main ]
    paths-ignore:
      - 'openapi/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-openapi:
    name: Synchronize OpenApi specifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Python packages
        working-directory: scripts/openapi
        run: pip install -U -r requirements.txt

      - name: Synchronize OpenApi specifications
        working-directory: scripts/openapi
        run: python openapi.py

      - name: Add and commit OpenApi specification changes
        uses: EndBug/add-and-commit@v9
        with:
          message: OpenApi specification changes
          add: openapi
          push: true
